# .goreleaser.yml
# Visit https://goreleaser.com for documentation.

version: 2

project_name: drako

before:
  hooks:
    - go mod tidy

builds:
  - id: drako
    main: ./cmd/drako
    binary: drako
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # Naming template compatible with uname output
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# -----------------------------------------------------------------------------
# Linux Packages (.deb, .rpm, AUR)
# -----------------------------------------------------------------------------

# Create .deb and .rpm packages
nfpms:
  -
    id: packages
    package_name: drako
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: "Lucky7xz"
    homepage: "https://github.com/lucky7xz/drako"
    maintainer: "Lucky7xz <lucky7xz@github.com>"
    description: "TUI-Deck launcher for terminal discipline."
    license: "AGPL-3.0"
    formats:
      - deb
      - rpm
    
    # Dependencies
    dependencies:
      - git

# Arch User Repository (AUR)
# Note: This requires a separate repo "drako-aur" or pushing to the AUR git repo directly.
# For now, we generate the PKGBUILD which can be pushed manually or via a separate pipeline.
aur:
  -
    name: drako-bin
    homepage: "https://github.com/lucky7xz/drako"
    description: "TUI-Deck launcher for terminal discipline."
    maintainers:
      - "Lucky7xz <lucky7xz@github.com>"
    license: "AGPL-3.0"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/drako-bin.git'
    package: |-
      # bin
      install -Dm755 "./drako" "${pkgdir}/usr/bin/drako"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/drako/LICENSE"
      
      # completions (if we add them later)
      # install -Dm644 "./completions/drako.bash" "${pkgdir}/usr/share/bash-completion/completions/drako"
      # install -Dm644 "./completions/drako.zsh" "${pkgdir}/usr/share/zsh/site-functions/_drako"
      # install -Dm644 "./completions/drako.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/drako.fish"

# -----------------------------------------------------------------------------
# macOS (Homebrew)
# -----------------------------------------------------------------------------

brews:
  -
    name: drako
    homepage: "https://github.com/lucky7xz/drako"
    description: "TUI-Deck launcher for terminal discipline."
    repository:
      owner: lucky7xz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    # Dependencies
    dependencies:
      - name: git

# -----------------------------------------------------------------------------
# Windows (Scoop)
# -----------------------------------------------------------------------------

scoops:
  -
    name: drako
    homepage: "https://github.com/lucky7xz/drako"
    description: "TUI-Deck launcher for terminal discipline."
    repository:
      owner: lucky7xz
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"

# -----------------------------------------------------------------------------
# Release
# -----------------------------------------------------------------------------

release:
  github:
    owner: lucky7xz
    name: drako
  draft: false
  prerelease: auto


